In [1]:
from pymoo.algorithms.nsga2 import NSGA2
from pymoo.factory import get_sampling, get_crossover, get_mutation, get_termination, get_problem
from pymoo.optimize import minimize
from pymoo.util.termination.default import MultiObjectiveDefaultTermination
from pymoo.factory import get_performance_indicator
import numpy as np
import time
import sys
import os 
import argparse



module_path = os.getcwd()+'/Problems/'
sys.path.append(module_path)
from Define_Problems import *

In [2]:
search_domain = np.column_stack([np.array([1,2]),np.array([3,4])])
search_domain

array([[1, 3],
       [2, 4]])

In [3]:
random_pick_X(sd= search_domain, size = 4) 

NameError: name 'args' is not defined

In [1]:
"sdaDFA".lower()

'sdadfa'

In [2]:
module_path = os.getcwd()+'/Problems/'
sys.path.append(module_path)
from Define_Problems import *

p_dict = {'bnh':BNH(lb=args.lb, up=args.ub), 
            'carside':Carside(lb=args.lb, up=args.ub), 
            'clutch':Clutch(lb=args.lb, up=args.ub), 
            'kursawe':Kursawe(lb=args.lb, up=args.ub), 
            'weldebeam':WeldedBeam(lb=args.lb, up=args.ub),
            "truss2d":Truss2D(lb=args.lb, up=args.ub),
            "tnk": Tnk(lb=args.lb, up=args.ub), 
            'osy':OSY(lb=args.lb, up=args.ub),
            "chankong":Chankong(lb=args.lb, up=args.ub),
            'test':Test(lb=args.lb, up=args.ub),
            'ctp1':CTP1(lb=args.lb, up=args.ub), 
            'pro1':PRO1(lb=args.lb, up=args.ub),
            'zdt1':ZDT1(lb=args.lb, up=args.ub,n_var=n_var),
            'zdt2':ZDT2(lb=args.lb, up=args.ub,n_var=n_var),
            'zdt3':ZDT3(lb=args.lb, up=args.ub,n_var=n_var),
            'zdt4':ZDT4(lb=args.lb, up=args.ub,n_var=n_var),
            'zdt5':ZDT5(lb=args.lb, up=args.ub,n_var=n_var),
            'zdt6':ZDT6(lb=args.lb, up=args.ub,n_var=n_var) }
for i in p_dict:
    p=p_dict(i)
    print(p)

NameError: name 'args' is not defined

In [5]:
p = Clutch(lb= [1,1,1,1,1], up=[2,2,2,2,2])
print(p)

# name: Clutch
# n_var: 5
# n_obj: 2
# n_constr: 19



In [55]:
from pymoo.model.problem import Problem
import autograd.numpy as anp



class BNH(Problem):

    def __init__(self,lb, up):
        xl = np.array(lb)
        xu = np.array(up)
        super().__init__(n_var=2, n_obj=2,  xl =[8,-3], xu=[9,2], n_constr=2, type_var=np.double)
        
    def _evaluate(self, x, out, *args, **kwargs):
        f1 = 4 * x[:, 0] ** 2 + 4 * x[:, 1] ** 2
        f2 = (x[:, 0] - 5) ** 2 + (x[:, 1] - 5) ** 2
        g1 = (1 / 25) * ((x[:, 0] - 5) ** 2 + x[:, 1] ** 2 - 25)
        g2 = -1 / 7.7 * ((x[:, 0] - 8) ** 2 + (x[:, 1] + 3) ** 2 - 7.7)

        out["F"] = anp.column_stack([f1, f2])
        out["G"] = anp.column_stack([g1, g2])

p = BNH(lb=[4,-3],up=[6,2])
print(p)
X = np.array([[1,2],
            [1,2]])

p.evaluate(X, return_values_of = ['F','G','CV'])

# name: BNH
# n_var: 2
# n_obj: 2
# n_constr: 2



(array([[20, 25],
        [20, 25]]),
 array([[-0.2       , -8.61038961],
        [-0.2       , -8.61038961]]),
 array([[0.],
        [0.]]))

In [34]:
python NSGA-II.py -p zdt4 -lb 2 5 6 1 -ub 7 7 8 9 -d 4 -eval 3000 -s 1000 -f zdt

128

In [56]:
'TnK'.lower()

'tnk'