In [1]:
import os, sys 
import pymoo 
import numpy as np 
from matplotlib import pyplot as plt 
from pymoo.factory import get_problem

In [8]:
#from problems import kur1
from pymoo.core.problem import Problem
class Kur1(Problem):
    def __init__(self, n_var=None, xl=None, xu = None,**kwargs):
        super().__init__(n_obj=2, n_constr=0,**kwargs)
    #define bound here
        self.xl= np.ones(n_var)*xl
        self.xu = np.ones(n_var)*xu
        self.n_var = n_var

        assert self.xl is not None, "Provide Search Domain"
        assert len(self.xu) == self.n_var
        
    def _evaluate(self,x, out, *args, **kwargs):
        #from i=1 to n-1
        #here, i would like to use vectorization to save cost
        power = np.column_stack([(-0.2)*np.sqrt(np.power(x[:,i],2)+np.power(x[:,i+1],2)) for i in range(self.n_var-1)])
        f1 = np.sum(-10*np.exp(power),axis=1)
        f2 = np.sum(np.power(abs(x),0.8) +5*np.sin(np.power(x,3)),axis=1)
        #exporting objective value     
        out['F'] = np.column_stack([f1,f2])

In [56]:
x = data_points

power = np.column_stack([(-0.2)*np.sqrt(np.power(x[:,i],2)+np.power(x[:,i+1],2)) for i in range(3-1)])
f1 = np.sum(-10*np.exp(power),axis=1)
f1

array([ -6.8745863 ,  -7.02409723,  -8.24604471, -10.77447327,
       -10.69217181,  -7.85355932,  -9.46743939,  -9.24679734,
        -7.13699043, -12.38411083])

In [9]:
kur1 = Kur1(n_var=3,xl=[-5,-5,-5],xu= [5,5,5])
kursawe = get_problem('kursawe')

In [10]:
print(kursawe.xl,kur1.xl)
print(kursawe.xu,kur1.xu)
print(kur1)
print(kursawe)

[-5. -5. -5.] [-5. -5. -5.]
[5. 5. 5.] [5. 5. 5.]
# name: Kur1
# n_var: 3
# n_obj: 2
# n_constr: 0

# name: Kursawe
# n_var: 3
# n_obj: 2
# n_constr: 0



In [5]:
data_points = np.random.uniform(-5,5,30).reshape(-1,3)

In [11]:
kur1.evaluate(data_points,return_values_of=['F'])

array([[ -7.44382543,   9.49846433],
       [-11.43435809,   7.36316562],
       [ -7.40052242,   7.76038443],
       [ -7.98628655,  11.21926618],
       [-10.02128521,   6.06669832],
       [ -9.55613918,   2.74445112],
       [ -6.15724462,  17.96037679],
       [ -6.60092627,  11.42265262],
       [ -7.9519767 ,  11.36268265],
       [-14.30448606,  13.48191273]])

In [12]:
kursawe.evaluate(data_points,return_values_of=['F'])

array([[ -7.44382543,   9.49846433],
       [-11.43435809,   7.36316562],
       [ -7.40052242,   7.76038443],
       [ -7.98628655,  11.21926618],
       [-10.02128521,   6.06669832],
       [ -9.55613918,   2.74445112],
       [ -6.15724462,  17.96037679],
       [ -6.60092627,  11.42265262],
       [ -7.9519767 ,  11.36268265],
       [-14.30448606,  13.48191273]])