In [1]:
import os, sys 
import pymoo 
import numpy as np 
from matplotlib import pyplot as plt 
from pymoo.factory import get_problem
sys.path.append('/Users/wuyoscar/Documents/Project/MOOP')

In [2]:
from problems import kur1
from pymoo.core.problem import Problem


In [13]:
from pymoo.core.problem import Problem
import numpy as np 
class Kur1(Problem):
    def __init__(self,n_var= None,**kwargs):
        super().__init__(n_obj=2, n_var=n_var, xl=-5.05, xu = 5,type_var= np.double, n_constr=0,**kwargs)

        
    def _evaluate(self,x, out, *args, **kwargs):
        #for i in range self.var-1
        power = np.column_stack([(-0.2)*np.sqrt(np.power(x[:,i],2)+np.power(x[:,i+1],2)) for i in range(self.n_var-1)])
        f1 = np.sum(-10*np.exp(power),axis=1)
        f2 = np.sum(np.power(abs(x),0.8) +5*np.sin(np.power(x,3)),axis=1)
        #exporting objective value     
        out['F'] = np.column_stack([f1,f2])
kur1 = Kur1(n_var=5)
kursawe = get_problem('kursawe')

In [14]:
print(kursawe.xl,kur1.xl)
print(kursawe.xu,kur1.xu)
print(kur1)
print(kursawe)

[-5. -5. -5.] [-5.05 -5.05 -5.05 -5.05 -5.05]
[5. 5. 5.] [5. 5. 5. 5. 5.]
# name: Kur1
# n_var: 5
# n_obj: 2
# n_constr: 0

# name: Kursawe
# n_var: 3
# n_obj: 2
# n_constr: 0



In [5]:
data_points = np.random.uniform(-5,5,30).reshape(-1,3)

In [11]:
kur1.evaluate(data_points,return_values_of=['F'])

array([[ -7.44382543,   9.49846433],
       [-11.43435809,   7.36316562],
       [ -7.40052242,   7.76038443],
       [ -7.98628655,  11.21926618],
       [-10.02128521,   6.06669832],
       [ -9.55613918,   2.74445112],
       [ -6.15724462,  17.96037679],
       [ -6.60092627,  11.42265262],
       [ -7.9519767 ,  11.36268265],
       [-14.30448606,  13.48191273]])

In [12]:
kursawe.evaluate(data_points,return_values_of=['F'])

array([[ -7.44382543,   9.49846433],
       [-11.43435809,   7.36316562],
       [ -7.40052242,   7.76038443],
       [ -7.98628655,  11.21926618],
       [-10.02128521,   6.06669832],
       [ -9.55613918,   2.74445112],
       [ -6.15724462,  17.96037679],
       [ -6.60092627,  11.42265262],
       [ -7.9519767 ,  11.36268265],
       [-14.30448606,  13.48191273]])

In [21]:
data_points = np.arange(0,4).reshape(-1,4)
data_points

array([[0, 1, 2, 3]])

In [22]:
x = data_points
f1 = -(-np.power(x[:,0]-2,2)-np.power(x[:,1]+3,2)-np.power(x[:,2]-5,2)-np.power(x[:,3]-4,2)+5)
f2 = -(np.sum(np.sin(x),axis=1)/(np.sum(np.power(x,2),axis=1)/100+1))