In [3]:
import os, sys 
import pymoo 
import numpy as np 
from matplotlib import pyplot as plt 
from pymoo.factory import get_problem
sys.path.append('/Users/wuyoscar/Documents/Project/MOOP')

In [4]:
from problems import kur1
from pymoo.core.problem import Problem


In [13]:
from pymoo.core.problem import Problem
import numpy as np 
class Kur1(Problem):
    def __init__(self,n_var= None,**kwargs):
        super().__init__(n_obj=2, n_var=n_var, xl=-5.05, xu = 5,type_var= np.double, n_constr=0,**kwargs)

        
    def _evaluate(self,x, out, *args, **kwargs):
        #for i in range self.var-1
        power = np.column_stack([(-0.2)*np.sqrt(np.power(x[:,i],2)+np.power(x[:,i+1],2)) for i in range(self.n_var-1)])
        f1 = np.sum(-10*np.exp(power),axis=1)
        f2 = np.sum(np.power(abs(x),0.8) +5*np.sin(np.power(x,3)),axis=1)
        #exporting objective value     
        out['F'] = np.column_stack([f1,f2])
kur1 = Kur1(n_var=5)
kursawe = get_problem('kursawe')

In [5]:
data_points = np.random.uniform(-5,5,30).reshape(-1,3)

In [11]:
kur1.evaluate(data_points,return_values_of=['F'])

array([[ -7.44382543,   9.49846433],
       [-11.43435809,   7.36316562],
       [ -7.40052242,   7.76038443],
       [ -7.98628655,  11.21926618],
       [-10.02128521,   6.06669832],
       [ -9.55613918,   2.74445112],
       [ -6.15724462,  17.96037679],
       [ -6.60092627,  11.42265262],
       [ -7.9519767 ,  11.36268265],
       [-14.30448606,  13.48191273]])

In [12]:
kursawe.evaluate(data_points,return_values_of=['F'])

array([[ -7.44382543,   9.49846433],
       [-11.43435809,   7.36316562],
       [ -7.40052242,   7.76038443],
       [ -7.98628655,  11.21926618],
       [-10.02128521,   6.06669832],
       [ -9.55613918,   2.74445112],
       [ -6.15724462,  17.96037679],
       [ -6.60092627,  11.42265262],
       [ -7.9519767 ,  11.36268265],
       [-14.30448606,  13.48191273]])

In [21]:
data_points = np.arange(0,4).reshape(-1,4)
data_points

array([[0, 1, 2, 3]])

In [22]:
x = data_points
f1 = -(-np.power(x[:,0]-2,2)-np.power(x[:,1]+3,2)-np.power(x[:,2]-5,2)-np.power(x[:,3]-4,2)+5)
f2 = -(np.sum(np.sin(x),axis=1)/(np.sum(np.power(x,2),axis=1)/100+1))

# Test TKLY1

In [5]:
class TKLY1(Problem):
    def __init__(self,**kwargs):
        super().__init__(n_var=4,n_obj=2, n_constr=0,**kwargs)
    #define bound here
        self.xl= np.array([0,0,0,0])
        self.xu = np.array([1,1,1,1])

        
    def _evaluate(self,x, out, *args, **kwargs):
        
        f1 = x[:,0]+0.1
        f2 = np.prod(2-np.exp(-np.power((x[:,1:]-0.1)/0.004,2))-0.8*np.exp(-np.power((x[:,1:]-0.9)/0.4,2)),axis=1)/(x[:,0]+0.1)
        #exporting objective value     
        out['F'] = np.column_stack([f1,f2])
tkly1 = TKLY1()

In [19]:
import math
# 0 1 2 3 DATA POINTS
f1 = 0.1
def f2(x):
    p1 = math.exp(-math.pow((x-0.1)/0.004,2))
    p2 = math.exp(-math.pow((x-0.9)/0.4,2))
    return 2-p1-0.8*p2
for i in range(1,4):
    print(f2(i))

1.2484695497492193
1.9995843402542761
1.9999999999991434


In [9]:
import math
math.pow(2,3)

8.0

In [20]:
(1.2484695497492193*1.9995843402542761*1.9999999999991434)/f1

49.92840321923553

In [21]:
tkly1.evaluate(np.array([0,1,2,3]).reshape(-1,4))

array([[ 0.1       , 49.92840322]])